// ============================================================================
// Partie A — Banque de questions textuelles (QCM enrichis) — Sprint F-FINAL
// ----------------------------------------------------------------------------
// Source : TradForge LAIS Banking Partie A (15 QCM par leçon, difficultés 1-3).
// Le moteur pioche 7 questions par tentative (2 faciles + 2 moyens + 3 durs)
// avec rotation anti-répétition. Mapping leçons : 1.1=intro · 1.2=macro ·
// 1.3=micro · 1.4=outils · 1.5=previsions.
// ============================================================================

import type { CoreLessonId } from "./evaluation-bank";
import type { BankItem } from "./assessment-picker";

const c = (a: string, b: string, cc: string, d: string) => [
  { id: "a", label: a },
  { id: "b", label: b },
  { id: "c", label: cc },
  { id: "d", label: d },
];

export const PART_A_BANK: Record<CoreLessonId, BankItem[]> = {
  intro: [
    { id: "1.1-Q1", difficulty: 1, correctId: "b", prompt: "L'analyse fondamentale cherche à déterminer :", choices: c("La tendance technique du marché", "La valeur intrinsèque d'un actif", "Les volumes de transactions", "La volatilité future"), explanation: "Elle se base sur les facteurs économiques et financiers pour évaluer la « juste valeur »." },
    { id: "1.1-Q2", difficulty: 1, correctId: "b", prompt: "Selon l'analyse fondamentale, le prix de marché :", choices: c("Coïncide toujours avec la valeur intrinsèque", "Peut s'écarter temporairement de la valeur intrinsèque", "Est indépendant des fondamentaux", "Détermine la valeur intrinsèque"), explanation: "Les marchés ne sont pas parfaitement efficients ; des divergences apparaissent." },
    { id: "1.1-Q3", difficulty: 1, correctId: "b", prompt: "Un des principes clés de l'analyse fondamentale est :", choices: c("L'efficience absolue des marchés", "Le retour à la moyenne à long terme", "L'absence de risque", "L'analyse des seuls graphiques"), explanation: "On s'attend à ce que le prix converge vers la valeur intrinsèque à long terme." },
    { id: "1.1-Q4", difficulty: 1, correctId: "b", prompt: "L'analyse fondamentale est particulièrement utile pour :", choices: c("Le trading haute fréquence", "Les stratégies d'investissement à long terme", "La détection de supports/résistances", "L'analyse des chandeliers"), explanation: "Elle se concentre sur les moteurs de valeur sur la durée." },
    { id: "1.1-Q5", difficulty: 1, correctId: "c", prompt: "Lequel n'est PAS un objectif de l'analyse fondamentale ?", choices: c("Identifier les actifs surévalués", "Comprendre les moteurs du marché", "Prédire le prix à 5 minutes", "Gérer les risques"), explanation: "L'AF n'a pas vocation à prévoir les mouvements de très court terme." },
    { id: "1.1-Q6", difficulty: 2, correctId: "b", prompt: "La valeur intrinsèque repose sur :", choices: c("Les rumeurs de marché", "Les facteurs économiques, financiers et qualitatifs", "Le sentiment des investisseurs", "Les ordres de bourse"), explanation: "Elle est basée sur une analyse approfondie des fondamentaux." },
    { id: "1.1-Q7", difficulty: 2, correctId: "b", prompt: "L'hypothèse d'efficience des marchés est :", choices: c("Totalement vraie dans tous les cas", "Remise en cause par l'analyse fondamentale", "Sans importance pour l'investisseur", "Une loi mathématique"), explanation: "L'analyse fondamentale postule que les marchés ne sont pas toujours efficients." },
    { id: "1.1-Q8", difficulty: 2, correctId: "b", prompt: "Le principe de « retour à la moyenne » implique que :", choices: c("Les prix ne reviennent jamais à leur moyenne", "Les prix tendent à revenir vers leur valeur intrinsèque", "La moyenne est toujours inférieure au prix", "Le prix moyen est la seule référence"), explanation: "C'est l'un des piliers de l'analyse fondamentale." },
    { id: "1.1-Q9", difficulty: 1, correctId: "b", prompt: "L'analyse fondamentale s'oppose à l'analyse technique car :", choices: c("Elle utilise des graphiques", "Elle s'intéresse aux causes sous-jacentes", "Elle est moins fiable", "Elle ne s'applique qu'aux actions"), explanation: "L'AT se concentre sur les prix et volumes, l'AF sur les fondamentaux." },
    { id: "1.1-Q10", difficulty: 1, correctId: "b", prompt: "Un investisseur qui utilise l'analyse fondamentale cherche à :", choices: c("Profiter des fluctuations de très court terme", "Exploiter les écarts entre prix et valeur intrinsèque", "Suivre les tendances des graphiques", "Ignorer les données économiques"), explanation: "L'objectif est d'acheter sous-évalué et vendre surévalué." },
    { id: "1.1-Q11", difficulty: 1, correctId: "b", prompt: "La « valeur intrinsèque » d'une devise dépend notamment :", choices: c("Des ordres de bourse", "De la santé économique du pays émetteur", "Du nombre de transactions", "De la météo"), explanation: "La santé économique (PIB, inflation, etc.) détermine la valeur d'une devise." },
    { id: "1.1-Q12", difficulty: 2, correctId: "b", prompt: "Pourquoi l'analyse fondamentale est-elle importante pour la gestion des risques ?", choices: c("Elle permet d'éviter toute perte", "Elle identifie les actifs soutenus par des fondamentaux solides", "Elle garantit des rendements élevés", "Elle est sans risque"), explanation: "En connaissant la solidité des fondamentaux, on peut mieux évaluer le risque." },
    { id: "1.1-Q13", difficulty: 3, correctId: "c", prompt: "L'analyse fondamentale est particulièrement adaptée aux marchés :", choices: c("Peu liquides", "Où les prix sont toujours justes", "Où des inefficiences peuvent exister", "Où l'information est parfaite"), explanation: "Les inefficiences créent des opportunités pour l'AF." },
    { id: "1.1-Q14", difficulty: 3, correctId: "b", prompt: "La valeur intrinsèque d'une entreprise est souvent estimée via :", choices: c("Les cours de bourse", "Les flux de trésorerie futurs actualisés", "Les volumes de transactions", "Les rumeurs"), explanation: "Le modèle DCF est l'un des plus utilisés." },
    { id: "1.1-Q15", difficulty: 3, correctId: "b", prompt: "Dans l'analyse fondamentale, la « convergence vers la valeur intrinsèque » :", choices: c("Est instantanée", "Peut prendre du temps", "N'arrive jamais", "Dépend des algorithmes"), explanation: "Les marchés peuvent rester irrationnels longtemps." },
  ],
  macro: [
    { id: "1.2-Q1", difficulty: 1, correctId: "b", prompt: "Une hausse surprise du PIB américain est généralement :", choices: c("Négative pour l'USD", "Positive pour l'USD", "Neutre", "Impossible à anticiper"), explanation: "Une croissance robuste attire les capitaux et peut maintenir les taux élevés." },
    { id: "1.2-Q2", difficulty: 1, correctId: "c", prompt: "L'indicateur qui mesure l'évolution des prix à la consommation est :", choices: c("Le PIB", "Le NFP", "L'IPC (CPI)", "Le PMI"), explanation: "L'Indice des Prix à la Consommation est la mesure standard de l'inflation." },
    { id: "1.2-Q3", difficulty: 1, correctId: "b", prompt: "Des taux d'intérêt plus élevés tendent à :", choices: c("Faire fuir les capitaux étrangers", "Attirer les capitaux étrangers", "Ne pas affecter la devise", "Réduire l'inflation immédiatement"), explanation: "Les investisseurs recherchent de meilleurs rendements, augmentant la demande pour la devise." },
    { id: "1.2-Q4", difficulty: 1, correctId: "b", prompt: "Un excédent commercial (exportations > importations) signifie :", choices: c("Une demande plus faible pour la devise nationale", "Une demande plus forte pour la devise nationale", "Une dépréciation automatique", "Aucun impact sur le forex"), explanation: "Les acheteurs étrangers ont besoin de la devise pour payer les exportations." },
    { id: "1.2-Q5", difficulty: 1, correctId: "b", prompt: "Les NFP (Non-Farm Payrolls) mesurent :", choices: c("Le nombre d'emplois dans l'agriculture", "Le nombre d'emplois créés hors secteur agricole", "Le taux de chômage uniquement", "Les salaires horaires moyens"), explanation: "Les NFP mesurent le nombre d'emplois créés ou perdus dans le secteur non agricole." },
    { id: "1.2-Q6", difficulty: 2, correctId: "b", prompt: "Une inflation élevée et persistante peut conduire la banque centrale à :", choices: c("Baisser ses taux directeurs", "Augmenter ses taux directeurs", "Ne rien changer", "Acheter des obligations"), explanation: "La politique restrictive (hausse des taux) vise à réduire l'inflation." },
    { id: "1.2-Q7", difficulty: 2, correctId: "c", prompt: "Parmi les indicateurs suivants, lequel est un indicateur avancé (leading) ?", choices: c("Taux de chômage", "PIB", "Permis de construire", "IPC"), explanation: "Les permis de construire changent avant que l'économie ne suive une tendance." },
    { id: "1.2-Q8", difficulty: 2, correctId: "b", prompt: "Lequel de ces indicateurs est un indicateur coïncident ?", choices: c("Spread de taux (inversion courbe)", "Production industrielle", "Coûts unitaires main-d'œuvre", "Nouvelles commandes équipement"), explanation: "La production industrielle évolue approximativement en même temps que l'économie." },
    { id: "1.2-Q9", difficulty: 2, correctId: "c", prompt: "Le taux de chômage est considéré comme un indicateur :", choices: c("Avancé", "Coïncident", "Retardé", "Non fiable"), explanation: "Les entreprises attendent d'être sûres de la reprise avant d'embaucher massivement." },
    { id: "1.2-Q10", difficulty: 2, correctId: "b", prompt: "Une hausse des prix du pétrole bénéficie généralement au :", choices: c("JPY", "CAD (Canada)", "EUR", "CHF"), explanation: "Le Canada est exportateur net de pétrole ; une hausse améliore sa balance." },
    { id: "1.2-Q11", difficulty: 2, correctId: "b", prompt: "L'« Average Hourly Earnings » aux USA mesure :", choices: c("Le nombre total d'emplois", "L'évolution des revenus salariaux", "Le taux de participation", "La productivité"), explanation: "Une forte croissance des salaires peut alimenter l'inflation (spirale prix-salaires)." },
    { id: "1.2-Q12", difficulty: 2, correctId: "b", prompt: "Les indices PMI (Purchasing Managers' Index) sont particulièrement surveillés car :", choices: c("Ils mesurent l'inflation passée", "Ils donnent une indication précoce de la santé des secteurs", "Ils remplacent le PIB", "Ils sont publiés annuellement"), explanation: "Les PMI sont des indicateurs avancés de l'activité économique." },
    { id: "1.2-Q13", difficulty: 3, correctId: "c", prompt: "Quelle catégorie d'indicateurs regroupe les décisions sur les taux d'intérêt et le forward guidance ?", choices: c("Indicateurs de croissance", "Indicateurs d'inflation", "Indicateurs liés à la politique monétaire", "Indicateurs de confiance"), explanation: "Ce sont des événements et communications ayant un impact fondamental majeur." },
    { id: "1.2-Q14", difficulty: 3, correctId: "b", prompt: "Une inversion de la courbe des taux (2Y > 10Y) est souvent interprétée comme :", choices: c("Un signal de croissance forte", "Un signe avant-coureur de récession", "Une politique monétaire expansionniste", "Un indicateur coïncident"), explanation: "L'inversion de la courbe est un indicateur avancé classique de récession." },
    { id: "1.2-Q15", difficulty: 3, correctId: "a", prompt: "Pourquoi les anticipations de changement de taux sont souvent plus importantes que les changements eux-mêmes ?", choices: c("Parce que les marchés anticipent et prixent à l'avance", "Parce que les banques centrales ne changent jamais les taux", "Parce que les taux sont fixes", "Parce que les anticipations n'ont aucun impact"), explanation: "Les marchés fonctionnent par anticipation ; le « priced in » est central." },
  ],
  micro: [
    { id: "1.3-Q1", difficulty: 1, correctId: "b", prompt: "Les données microéconomiques se concentrent principalement sur :", choices: c("La politique monétaire", "Les performances individuelles des entreprises", "Les taux de change", "Les indicateurs de confiance"), explanation: "La microéconomie analyse les unités économiques individuelles (entreprises, ménages)." },
    { id: "1.3-Q2", difficulty: 1, correctId: "b", prompt: "Le bilan d'une entreprise respecte toujours l'équation :", choices: c("Actif = Passif − Equity", "Actif = Passif + Equity", "Equity = Passif − Actif", "Passif = Actif + Equity"), explanation: "Actif = Passif + Equity (fondamental de la comptabilité)." },
    { id: "1.3-Q3", difficulty: 1, correctId: "b", prompt: "Le compte de résultat mesure :", choices: c("La santé financière à un instant T", "La performance sur une période (revenus, coûts, bénéfices)", "Les flux de trésorerie", "La valeur de l'entreprise"), explanation: "Il présente les revenus et charges sur une période donnée." },
    { id: "1.3-Q4", difficulty: 1, correctId: "a", prompt: "Une marge nette de 25 % signifie que :", choices: c("L'entreprise dégage 25 % de bénéfice net par rapport à ses revenus", "L'entreprise a 25 % de dette", "25 % des actifs sont liquides", "Le ROE est de 25 %"), explanation: "Marge nette = Bénéfice net / Revenus." },
    { id: "1.3-Q5", difficulty: 1, correctId: "b", prompt: "Le ratio dette/équité (D/E) évalue :", choices: c("La rentabilité", "Le niveau d'endettement", "La liquidité", "La croissance des ventes"), explanation: "Il indique le niveau d'endettement par rapport aux fonds propres." },
    { id: "1.3-Q6", difficulty: 1, correctId: "a", prompt: "Le ROE (Return on Equity) mesure :", choices: c("La rentabilité des capitaux propres", "La liquidité de l'entreprise", "L'endettement total", "La croissance des revenus"), explanation: "ROE = Bénéfice net / Capitaux propres." },
    { id: "1.3-Q7", difficulty: 2, correctId: "a", prompt: "Un flux de trésorerie libre (Free Cash Flow) élevé indique :", choices: c("Une forte capacité à générer de la liquidité disponible", "Une forte dette", "Une faible rentabilité", "Un besoin de financement externe"), explanation: "Le FCF représente la liquidité générée après investissements." },
    { id: "1.3-Q8", difficulty: 2, correctId: "a", prompt: "Apple Inc. affichait en 2023 une marge nette de 25 % et un P/E de 28. Cela suggère :", choices: c("Une valorisation juste proche de la valeur intrinsèque", "Une entreprise en difficulté", "Un ratio D/E élevé", "Une faible croissance"), explanation: "Marge élevée + P/E raisonnable = valorisation alignée avec les fondamentaux." },
    { id: "1.3-Q9", difficulty: 2, correctId: "b", prompt: "Tesla affichait en 2022 un P/E de 50+. Cela reflète principalement :", choices: c("Une valorisation discount", "Des attentes de croissance futures très élevées", "Une faible volatilité", "Un endettement nul"), explanation: "Un P/E élevé indique que le marché anticipe une forte croissance future." },
    { id: "1.3-Q10", difficulty: 2, correctId: "b", prompt: "Le « Current Ratio » (actifs courants / dettes courantes) mesure :", choices: c("La rentabilité à long terme", "La liquidité et la capacité à payer les dettes à court terme", "L'efficacité opérationnelle", "La croissance des ventes"), explanation: "< 1 = risque de défaut à court terme." },
    { id: "1.3-Q11", difficulty: 3, correctId: "a", prompt: "Pourquoi un ROE élevé via un levier financier (dette) peut être fragile ?", choices: c("Parce que la dette augmente le risque financier", "Parce que la dette est toujours mauvaise", "Parce que le ROE ne compte pas la dette", "Parce que les actionnaires n'aiment pas la dette"), explanation: "ROE artificiellement gonflé par la dette = risque de faillite accru." },
    { id: "1.3-Q12", difficulty: 2, correctId: "b", prompt: "Dans l'analyse d'un bilan, « Equity » représente :", choices: c("Les dettes totales", "La valeur nette appartenant aux actionnaires", "Les actifs immobilisés", "Les stocks et créances"), explanation: "Equity = Actif − Passif (fonds propres)." },
    { id: "1.3-Q13", difficulty: 3, correctId: "b", prompt: "Une entreprise avec des revenus en hausse de 51 % (Tesla 2022) mais un P/E de 50 est :", choices: c("Sous-évaluée", "Potentiellement surévaluée si la croissance ne se matérialise pas", "Toujours un bon investissement", "Sans risque"), explanation: "Le P/E élevé price une croissance future qui peut ne pas se réaliser." },
    { id: "1.3-Q14", difficulty: 3, correctId: "b", prompt: "Le « Quick Ratio » diffère du « Current Ratio » car il exclut :", choices: c("Les créances clients", "Les stocks (inventaire)", "Les liquidités", "Les dettes à long terme"), explanation: "Quick Ratio = (Actifs courants − Stocks) / Dettes courantes (plus conservateur)." },
    { id: "1.3-Q15", difficulty: 3, correctId: "b", prompt: "Pourquoi les marges brutes et nettes doivent être analysées ensemble ?", choices: c("Parce qu'elles mesurent la même chose", "Parce que l'écart entre les deux révèle l'efficacité opérationnelle et les coûts indirects", "Parce que la marge brute suffit", "Parce que la marge nette n'a pas d'importance"), explanation: "Marge brute − coûts opérationnels = marge nette. Un écart anormal signale un problème." },
  ],
  outils: [
    { id: "1.4-Q1", difficulty: 1, correctId: "a", prompt: "Le ratio P/E (Price-to-Earnings) mesure :", choices: c("La valorisation par rapport aux bénéfices", "La rentabilité des capitaux propres", "Le niveau d'endettement", "La liquidité"), explanation: "P/E = Cours / BPA. Indique combien d'années de bénéfices sont payées." },
    { id: "1.4-Q2", difficulty: 1, correctId: "a", prompt: "Le modèle DCF (Discounted Cash Flow) estime la valeur intrinsèque via :", choices: c("Les flux de trésorerie futurs actualisés", "Le cours de bourse moyen", "Les volumes de transactions", "Le sentiment des analystes"), explanation: "DCF = somme des FCF futurs actualisés + valeur terminale." },
    { id: "1.4-Q3", difficulty: 1, correctId: "a", prompt: "L'analyse sectorielle vise à :", choices: c("Identifier les tendances et défis spécifiques à un secteur", "Prédire le cours du pétrole", "Mesurer l'inflation", "Calculer le PIB"), explanation: "Elle compare les performances au sein d'un secteur pour identifier leaders et laggards." },
    { id: "1.4-Q4", difficulty: 1, correctId: "a", prompt: "L'analyse SWOT examine :", choices: c("Les forces, faiblesses, opportunités et menaces", "Les salaires et les coûts", "Les taux d'intérêt et l'inflation", "Les volumes et la volatilité"), explanation: "SWOT = outil stratégique d'évaluation qualitative." },
    { id: "1.4-Q5", difficulty: 1, correctId: "b", prompt: "Un ratio D/E < 1 est généralement interprété comme :", choices: c("Un endettement excessif", "Une santé financière raisonnable", "Une rentabilité faible", "Une liquidité insuffisante"), explanation: "Moins de dette que de fonds propres = structure financière conservative." },
    { id: "1.4-Q6", difficulty: 2, correctId: "a", prompt: "Le P/B (Price-to-Book) compare :", choices: c("Le cours de bourse à la valeur comptable par action", "Le bénéfice net aux dividendes", "La dette aux revenus", "Le cours au flux de trésorerie"), explanation: "Utile pour évaluer les entreprises à fort actif tangible (banques, industrie)." },
    { id: "1.4-Q7", difficulty: 2, correctId: "b", prompt: "Dans un modèle DCF, le WACC représente :", choices: c("Le taux de croissance des revenus", "Le coût moyen pondéré du capital", "Le bénéfice par action", "Le taux d'actualisation du risque pays"), explanation: "WACC = coût moyen pondéré du capital, paramètre le plus sensible du DCF." },
    { id: "1.4-Q8", difficulty: 2, correctId: "b", prompt: "Pourquoi le P/E d'Apple (28 en 2023) peut être considéré comme supérieur à la moyenne du secteur ?", choices: c("Parce qu'Apple est en faillite", "Parce que la prime reflète la qualité, l'écosystème et la croissance des services", "Parce que le secteur tech a un P/E moyen de 50", "Parce que le P/E n'a pas d'importance"), explanation: "Une prime est justifiée par des avantages concurrentiels durables." },
    { id: "1.4-Q9", difficulty: 2, correctId: "b", prompt: "La comparaison Tesla vs Ford (P/E 50 vs 10) reflète :", choices: c("Que Ford est toujours meilleur", "Des perspectives de croissance et de risque différentes", "Que Tesla est sous-évaluée", "Que le P/E est inutile"), explanation: "Un P/E élevé = croissance attendue ; un P/E bas = maturité ou difficultés." },
    { id: "1.4-Q10", difficulty: 2, correctId: "a", prompt: "L'analyse comparative (peer comparison) permet de :", choices: c("Identifier les écarts de valorisation justifiés ou non", "Prédire les taux de change", "Mesurer l'inflation", "Calculer le PIB"), explanation: "Comparer avec des pairs aide à détecter surévaluation ou sous-évaluation." },
    { id: "1.4-Q11", difficulty: 3, correctId: "a", prompt: "Pourquoi le modèle DCF est-il particulièrement sensible au WACC ?", choices: c("Parce que +1 % WACC = −15 à −20 % valorisation", "Parce que le WACC n'a pas d'impact", "Parce que le WACC est fixe", "Parce que le WACC remplace la croissance"), explanation: "Le WACC est le paramètre le plus critique du DCF." },
    { id: "1.4-Q12", difficulty: 2, correctId: "b", prompt: "Dans l'analyse SWOT de Netflix, « Base d'abonnés mondiale » est une :", choices: c("Faiblesse", "Force", "Menace", "Opportunité"), explanation: "C'est un avantage concurrentiel structurel." },
    { id: "1.4-Q13", difficulty: 3, correctId: "a", prompt: "Pourquoi un multiple absolu (ex: P/E 30) peut être trompeur ?", choices: c("Parce qu'il dépend du secteur et du cycle économique", "Parce que 30 est toujours cher", "Parce que les multiples ne servent à rien", "Parce que le P/E est illégal"), explanation: "P/E 30 = cher (utility) vs normal (tech croissance). Le contexte sectoriel est essentiel." },
    { id: "1.4-Q14", difficulty: 3, correctId: "b", prompt: "La « valeur terminale » dans un DCF représente généralement :", choices: c("10-20 % de la valorisation totale", "60-80 % de la valorisation totale", "0 % de la valorisation", "La dette nette"), explanation: "La majeure partie de la valeur vient des flux lointains, d'où la sensibilité aux hypothèses." },
    { id: "1.4-Q15", difficulty: 3, correctId: "b", prompt: "Pourquoi l'analyse fondamentale d'une banque diffère-t-elle de celle d'une entreprise tech ?", choices: c("Parce que les banques n'ont pas de bilan", "Parce que les métriques clés sont différentes (NIM, CET1, provisions vs ARR, churn)", "Parce que les banques ne sont pas cotées", "Parce que l'AF ne s'applique pas aux banques"), explanation: "Chaque secteur a ses propres ratios et drivers de valeur." },
  ],
  previsions: [
    { id: "1.5-Q1", difficulty: 1, correctId: "a", prompt: "Les prévisions financières combinent :", choices: c("Données historiques, tendances sectorielles et projections économiques", "Seulement des données historiques", "Seulement des opinions d'analystes", "Des graphiques techniques uniquement"), explanation: "La prévision est un processus multi-inputs." },
    { id: "1.5-Q2", difficulty: 1, correctId: "a", prompt: "L'analyse des tendances historiques vise à :", choices: c("Identifier des patterns dans les revenus et bénéfices", "Prédire la météo", "Calculer le PIB", "Mesurer l'inflation"), explanation: "Elle repose sur la continuité des performances passées." },
    { id: "1.5-Q3", difficulty: 1, correctId: "b", prompt: "Une guidance « raised » (revue à la hausse) par une entreprise est généralement interprétée comme :", choices: c("Un signal négatif", "Un signal positif sur les perspectives", "Sans impact", "Une manipulation de marché"), explanation: "La direction confirme une performance meilleure que prévu." },
    { id: "1.5-Q4", difficulty: 1, correctId: "b", prompt: "Dans la modélisation par scénarios, on prépare généralement :", choices: c("Un seul scénario optimiste", "Trois scénarios (optimiste, neutre, pessimiste)", "Un scénario unique sans risque", "Aucun scénario"), explanation: "La préparation multi-scénarios permet d'évaluer l'asymétrie risque/rendement." },
    { id: "1.5-Q5", difficulty: 2, correctId: "b", prompt: "La « valeur espérée » dans un planificateur de scénarios est calculée comme :", choices: c("La moyenne simple des trois scénarios", "Σ(probabilité × valorisation scénario)", "Le scénario le plus probable uniquement", "La médiane des scénarios"), explanation: "C'est la somme pondérée des valeurs par leurs probabilités." },
    { id: "1.5-Q6", difficulty: 2, correctId: "a", prompt: "Pourquoi la guidance est-elle souvent plus importante que le beat/miss actuel ?", choices: c("Parce qu'elle oriente les attentes futures du marché", "Parce que le passé n'a pas d'importance", "Parce que les résultats actuels sont faux", "Parce que la guidance est obligatoire"), explanation: "Le marché anticipe ; une guidance lowered peut faire chuter le cours malgré un beat." },
    { id: "1.5-Q7", difficulty: 2, correctId: "b", prompt: "Un scénario de prévision « sans risque » est :", choices: c("Idéal pour la prise de décision", "Un biais cognitif dangereux", "Recommandé par les banques centrales", "Toujours exact"), explanation: "Ne pas préparer de scénario adverse = absence de plan de sortie." },
    { id: "1.5-Q8", difficulty: 2, correctId: "a", prompt: "Si la valeur espérée d'une action est supérieure au cours actuel, cela suggère :", choices: c("Une asymétrie positive (upside)", "Une asymétrie négative (downside)", "Que le marché a toujours raison", "Qu'il faut vendre immédiatement"), explanation: "Cela indique un potentiel de sous-évaluation selon les hypothèses du modèle." },
    { id: "1.5-Q9", difficulty: 2, correctId: "b", prompt: "Un beat d'EPS de 1-2 % par rapport au consensus est généralement considéré comme :", choices: c("Un fort signal", "Un bruit de marché faible", "Une catastrophe", "Un dividende"), explanation: "Un écart faible peut être dû à des facteurs comptables non récurrents." },
    { id: "1.5-Q10", difficulty: 2, correctId: "b", prompt: "Pourquoi faut-il toujours définir une invalidation avant une entrée en position ?", choices: c("Parce que c'est une règle de l'AMF", "Parce qu'un scénario sans sortie = biais de confirmation", "Parce que les stops sont interdits", "Parce que l'invalidation est optionnelle"), explanation: "Définir la sortie avant l'entrée évite le biais de rationalisation post-hoc." },
    { id: "1.5-Q11", difficulty: 2, correctId: "b", prompt: "La prévision du prix de l'or à 2000 $/once « en cas de tensions géopolitiques » est un exemple de :", choices: c("Analyse technique", "Scénario conditionnel macroéconomique", "Manipulation de marché", "Donnée historique"), explanation: "C'est une prévision dépendante d'un catalyseur externe." },
    { id: "1.5-Q12", difficulty: 3, correctId: "a", prompt: "Pourquoi les prévisions de taux d'intérêt par la Fed impactent-elles les obligations ?", choices: c("Parce que les obligations sont sensibles aux taux (duration)", "Parce que la Fed achète des obligations", "Parce que les obligations ne rapportent rien", "Parce que les taux sont fixes"), explanation: "La duration mesure la sensibilité du prix d'une obligation aux variations de taux." },
    { id: "1.5-Q13", difficulty: 3, correctId: "a", prompt: "Un scénario pessimiste pour l'industrie automobile (-10 % en cas de récession) illustre :", choices: c("L'importance du stress testing", "Que l'automobile est sans risque", "Que la récession n'existe pas", "Que les scénarios sont inutiles"), explanation: "Le stress testing évalue la résilience face aux chocs macro." },
    { id: "1.5-Q14", difficulty: 2, correctId: "b", prompt: "La probabilité totale des trois scénarios (optimiste, neutre, pessimiste) doit être :", choices: c("Supérieure à 100 %", "Égale à 100 %", "Inférieure à 50 %", "Variable selon le marché"), explanation: "C'est une distribution de probabilités complète." },
    { id: "1.5-Q15", difficulty: 3, correctId: "a", prompt: "Pourquoi les prévisions à long terme (5-10 ans) sont-elles intrinsèquement moins fiables ?", choices: c("Parce que l'incertitude cumulée des hypothèses croît exponentiellement", "Parce que les analystes sont incompétents", "Parce que les données historiques n'existent pas", "Parce que les marchés sont parfaits"), explanation: "Les petites variations d'hypothèses se compoundent sur la durée." },
  ],
};
