// ============================================================================
// Partie B — Banque de questions widgets & visuels (QCM) — Sprint F-FINAL
// ----------------------------------------------------------------------------
// Source : TradForge LAIS Banking Partie B (widgets mappés par leçon,
// difficultés 1-3). Le cœur analytique de TradForge (pondération 70 %).
// Chaque item porte le widget testé + un visuel support (V1, conservé
// temporairement jusqu'aux équivalents V2). Le moteur pioche 7 questions par
// tentative (2 faciles + 2 moyens + 3 durs) avec rotation anti-répétition.
// Mapping leçons : 1.1=intro · 1.2=macro · 1.3=micro · 1.4=outils · 1.5=previsions.
// ============================================================================

import type { CoreLessonId } from "./evaluation-bank";
import type { BankItem } from "./assessment-picker";

const c = (a: string, b: string, cc: string, d: string) => [
  { id: "a", label: a },
  { id: "b", label: b },
  { id: "c", label: cc },
  { id: "d", label: d },
];

export const PART_B_BANK: Record<CoreLessonId, BankItem[]> = {
  intro: [
    { id: "1.1-WQ1", difficulty: 1, correctId: "b", widget: "MarketDriverVisualizer", visualId: "a17", prompt: "Dans le MarketDriverVisualizer, la chaîne causale s'affiche comme :", choices: c("Un tableau de chiffres", "Driver → Canal → Actif impacté → Invalidation", "Un graphique en camembert", "Une liste alphabétique"), explanation: "La logique est la transmission causale avec condition de sortie explicite." },
    { id: "1.1-WQ2", difficulty: 1, correctId: "c", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Le MacroRegimeRadar affiche 4 régimes principaux. Lequel correspond à « croissance forte + inflation modérée » ?", choices: c("Stagflation", "Récession", "Goldilocks", "Déflation"), explanation: "Goldilocks = croissance saine + inflation contrôlée." },
    { id: "1.1-WQ3", difficulty: 2, correctId: "b", widget: "MarketDriverVisualizer", visualId: "a17", prompt: "Dans le MarketDriverVisualizer, l'« invalidation » représente :", choices: c("Une erreur de calcul", "La condition de sortie qui rend la thèse caduque", "Un achat forcé", "Une news positive"), explanation: "C'est le mécanisme de gestion du risque : quand la thèse est invalidée, on sort." },
    { id: "1.1-WQ4", difficulty: 2, correctId: "b", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Sur le MacroRegimeRadar, l'axe « Liquidité » mesure principalement :", choices: c("Le volume des transactions", "La politique monétaire (QE/QT, taux)", "Le nombre d'employés", "Le PIB"), explanation: "Liquidité = politique monétaire, spreads de crédit, conditions financières." },
    { id: "1.1-WQ5", difficulty: 2, correctId: "b", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Le régime « Stagflation » sur le radar implique généralement :", choices: c("Actions haussières + obligations haussières", "Croissance faible + inflation élevée", "Croissance forte + inflation nulle", "Déflation + chômage faible"), explanation: "Stagflation = stagnation économique + inflation persistante." },
    { id: "1.1-WQ6", difficulty: 2, correctId: "b", widget: "MarketDriverVisualizer", visualId: "a17", prompt: "Dans le MarketDriverVisualizer, si le driver sélectionné est « NFP fort », le canal de transmission vers l'USD est :", choices: c("Politique fiscale", "Politique monétaire (taux réels, anticipations Fed)", "Balance commerciale", "Rien, le NFP n'impacte pas l'USD"), explanation: "NFP fort → Fed hawkish → taux ↑ → USD ↑." },
    { id: "1.1-WQ7", difficulty: 2, correctId: "d", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Le MacroRegimeRadar utilise un polygone à 6 axes. Lequel de ces axes n'est PAS affiché ?", choices: c("PIB", "Inflation", "Taux directeurs", "Dividendes"), explanation: "Les 6 axes sont : PIB, IPC, Taux, Liquidité, Sentiment, Crédit." },
    { id: "1.1-WQ8", difficulty: 3, correctId: "b", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Si le radar indique un score élevé sur « Inflation » et « Taux », mais faible sur « PIB », le régime probable est :", choices: c("Expansion", "Stagflation", "Goldilocks", "Récession pure"), explanation: "Inflation haute + croissance faible = Stagflation." },
    { id: "1.1-WQ9", difficulty: 3, correctId: "a", widget: "MarketDriverVisualizer", visualId: "a17", prompt: "Dans le MarketDriverVisualizer, l'invalidation d'un driver « PIB fort » pourrait être :", choices: c("Une révision à la baisse du PIB", "Une hausse des salaires", "Une baisse du chômage", "Un excédent commercial"), explanation: "Si le PIB est révisé à la baisse, la thèse de croissance forte s'effondre." },
    { id: "1.1-WQ10", difficulty: 3, correctId: "b", widget: "MacroRegimeRadar", visualId: "a11", prompt: "Pourquoi le MacroRegimeRadar est-il plus utile qu'un indicateur macro isolé ?", choices: c("Parce qu'il est plus coloré", "Parce qu'il force la lecture multi-dimensionnelle (croisement de plusieurs facteurs)", "Parce qu'il prédit le cours exact", "Parce qu'il remplace l'analyse technique"), explanation: "La macro est multi-factorielle ; le radar évite le diagnostic mono-variable." },
  ],
  macro: [
    { id: "1.2-WQ1", difficulty: 1, correctId: "b", widget: "MacroDashboard", visualId: "a5", prompt: "Le MacroDashboard affiche 11 indicateurs sous forme de :", choices: c("Graphique linéaire unique", "Tuiles synthèse (Réel / Consensus / Précédent)", "Tableau Excel", "Carte géographique"), explanation: "C'est un command center avec filtres par catégorie et modal détail." },
    { id: "1.2-WQ2", difficulty: 1, correctId: "b", widget: "EconomicCycleWheel", visualId: "a1", prompt: "Dans l'EconomicCycleWheel, la phase « Récession » favorise généralement :", choices: c("Les actions cycliques", "L'or et les obligations souveraines", "Les devises des marchés émergents", "Les matières premières industrielles"), explanation: "Récession = fuite vers la qualité (safe havens)." },
    { id: "1.2-WQ3", difficulty: 1, correctId: "b", widget: "FedSimulator", visualId: "a1", prompt: "Le FedSimulator utilise deux sliders principaux :", choices: c("PIB et balance commerciale", "CPI et NFP", "Or et pétrole", "Actions et obligations"), explanation: "La matrice décision Fed croise inflation et emploi." },
    { id: "1.2-WQ4", difficulty: 2, correctId: "b", widget: "NfpInterpreter", visualId: "a4", prompt: "Dans le NfpInterpreter, une surprise de +2σ (sigma) est interprétée comme :", choices: c("Un bruit statistique", "Un signal fort susceptible de déclencher une réaction Fed", "Sans impact sur les marchés", "Un indicateur retardé"), explanation: ">2σ = magnitude exceptionnelle = réaction institutionnelle probable." },
    { id: "1.2-WQ5", difficulty: 2, correctId: "b", widget: "YieldCurveVisualizer", visualId: "a14", prompt: "Le YieldCurveVisualizer affiche une courbe « inversée » quand :", choices: c("Les taux longs sont supérieurs aux taux courts", "Les taux courts sont supérieurs aux taux longs (ex: 2Y > 10Y)", "Tous les taux sont nuls", "La Fed baisse les taux"), explanation: "Inversion 2Y/10Y = signal récession classique." },
    { id: "1.2-WQ6", difficulty: 2, correctId: "b", widget: "GdpCpiInterpreters", visualId: "a1", prompt: "Dans le GdpCpiInterpreters, la combinaison PIB fort + CPI bas correspond au régime :", choices: c("Stagflation", "Goldilocks", "Récession", "Hyperinflation"), explanation: "Croissance saine + inflation maîtrisée = environnement idéal." },
    { id: "1.2-WQ7", difficulty: 2, correctId: "a", widget: "IntermarketCorrelationMap", visualId: "a13", prompt: "L'IntermarketCorrelationMap affiche une corrélation négative (rouge) entre DXY et EUR/USD. Cela signifie :", choices: c("Quand le dollar monte, l'euro tend à baisser", "Les deux montent ensemble", "Aucun lien entre les deux", "La corrélation est décorative"), explanation: "Corrélation négative = mouvements inverses." },
    { id: "1.2-WQ8", difficulty: 2, correctId: "b", widget: "MacroIndicatorLab", visualId: "a2", prompt: "Dans le MacroIndicatorLab, la « surprise » est calculée comme :", choices: c("Consensus − Réel", "Réel − Consensus", "Réel + Consensus", "Réel / Consensus"), explanation: "Surprise = Réel − Consensus (beat si > 0, miss si < 0)." },
    { id: "1.2-WQ9", difficulty: 2, correctId: "a", widget: "MacroRelationshipEngine", visualId: "a2", prompt: "Le MacroRelationshipEngine affiche une chaîne : CPI ↑ → Fed hawkish → USD ↑. Le mécanisme de transmission est :", choices: c("La politique monétaire restrictive renforce la devise", "L'inflation affaiblit toujours la devise", "La Fed achète des devises", "Le USD monte sans raison"), explanation: "Hawkish = taux ↑ → attrait des capitaux → devise ↑." },
    { id: "1.2-WQ10", difficulty: 2, correctId: "b", widget: "YieldCurveVisualizer", visualId: "a14", prompt: "Sur le YieldCurveVisualizer, une courbe « plate » suggère :", choices: c("Une croissance explosive imminente", "Une transition ou incertitude économique", "Une inflation galopante", "Un défaut souverain"), explanation: "Courbe plate = marché incertain sur la direction future." },
    { id: "1.2-WQ11", difficulty: 2, correctId: "b", widget: "MacroDashboard", visualId: "a5", prompt: "Dans le MacroDashboard, un indicateur affichant « Beat » avec un consensus dépassé signifie :", choices: c("Le réel est inférieur au consensus", "Le réel est supérieur au consensus", "Le réel égale le consensus", "L'indicateur est annulé"), explanation: "Beat = réel > consensus (surprise positive)." },
    { id: "1.2-WQ12", difficulty: 3, correctId: "a", widget: "EconomicCycleWheel", visualId: "a1", prompt: "L'EconomicCycleWheel permet de distinguer :", choices: c("Le cycle économique (phases macro) de la tendance prix (direction)", "Le cycle des lave-vaisselle", "Le PIB et l'inflation uniquement", "Les taux et les devises"), explanation: "Cycle ≠ tendance. La roue montre les phases macro, pas les graphiques de prix." },
    { id: "1.2-WQ13", difficulty: 3, correctId: "b", widget: "FedSimulator", visualId: "a1", prompt: "Dans le FedSimulator, la combinaison CPI 5 % + NFP 300K produit probablement une décision :", choices: c("Dovish (baisse des taux)", "Hawkish (maintien ou hausse des taux)", "Neutre sans changement", "QE illimité"), explanation: "Inflation chaude + emploi fort = Fed restrictive." },
    { id: "1.2-WQ14", difficulty: 3, correctId: "b", widget: "IntermarketCorrelationMap", visualId: "a13", prompt: "Sur l'IntermarketCorrelationMap, une cassure de corrélation historique (gris) entre l'or et le DXY peut signaler :", choices: c("Un retour à la normale", "Un choc systémique ou un changement de régime macro", "Une erreur de données", "Rien de particulier"), explanation: "Décorrélation soudaine = crise ou changement de paradigme." },
    { id: "1.2-WQ15", difficulty: 3, correctId: "b", widget: "NfpInterpreter", visualId: "a4", prompt: "Le NfpInterpreter croise le NFP avec les salaires horaires moyens car :", choices: c("Les salaires sont décoratifs", "La pression salariale alimente l'inflation (spirale prix-salaires)", "Les salaires n'ont aucun lien avec la Fed", "Le NFP seul suffit"), explanation: "NFP + salaires = lecture complète du marché du travail pour la Fed." },
  ],
  micro: [
    { id: "1.3-WQ1", difficulty: 1, correctId: "d", widget: "CompanyHealthScore", visualId: "a6", prompt: "Le CompanyHealthScore agrège 4 dimensions. Laquelle n'est PAS incluse ?", choices: c("Croissance", "Marges", "Dette", "Dividende"), explanation: "Les 4 dimensions sont : Croissance, Marges, Dette, Liquidité." },
    { id: "1.3-WQ2", difficulty: 1, correctId: "a", widget: "BalanceSheetExplorer", visualId: "a8", prompt: "Dans le BalanceSheetExplorer, l'équation fondamentale est :", choices: c("Actif = Passif + Equity", "Revenus = Bénéfices + Dividendes", "Dette = Actif − Cash", "Equity = Dette × ROE"), explanation: "C'est la base de la comptabilité en partie double." },
    { id: "1.3-WQ3", difficulty: 1, correctId: "b", widget: "CompanyDashboard", visualId: "a3", prompt: "Le CompanyDashboard affiche les KPI sous forme de :", choices: c("Graphique en camembert", "Tuiles synthèse avec lecture croisée", "Tableau Excel brut", "Carte géographique"), explanation: "C'est une vue synthèse rapide pour le diagnostic micro." },
    { id: "1.3-WQ4", difficulty: 2, correctId: "b", widget: "CompanyHealthScore", visualId: "a6", prompt: "Un score CompanyHealthScore > 75 est interprété comme :", choices: c("Un red flag immédiat", "Une qualité institutionnelle", "Une valorisation excessive", "Un risque de faillite"), explanation: "> 75 = entreprise solide sur les 4 dimensions." },
    { id: "1.3-WQ5", difficulty: 2, correctId: "b", widget: "FinancialRatios", visualId: "a7", prompt: "Dans le FinancialRatios, un ROE > 15 % est généralement considéré comme :", choices: c("Faible", "De qualité institutionnelle", "Négatif", "Sans importance"), explanation: "Seuil classique de rentabilité des fonds propres." },
    { id: "1.3-WQ6", difficulty: 2, correctId: "b", widget: "FinancialRatios", visualId: "a7", prompt: "Le Current Ratio dans le FinancialRatios mesure :", choices: c("La rentabilité", "La liquidité à court terme (actifs courants / dettes courantes)", "L'endettement total", "La croissance"), explanation: "< 1 = risque de défaut à court terme." },
    { id: "1.3-WQ7", difficulty: 2, correctId: "b", widget: "BalanceSheetExplorer", visualId: "a8", prompt: "Dans le BalanceSheetExplorer, si Actif < Passif, l'entreprise est :", choices: c("Très rentable", "Techniquement insolvable", "En croissance", "Sous-évaluée"), explanation: "L'équilibre comptable est rompu = insolvabilité technique." },
    { id: "1.3-WQ8", difficulty: 2, correctId: "b", widget: "CompanyDashboard", visualId: "a3", prompt: "Le CompanyDashboard suggère qu'un seul KPI « ne raconte rien ». Pourquoi ?", choices: c("Parce que les KPI sont faux", "Parce qu'il faut croiser Croissance + Marges + Dette + Cash", "Parce que le dashboard est inutile", "Parce que les marchés sont efficients"), explanation: "La microéconomie exige la lecture croisée (ex: profitable + surendetté = fragile)." },
    { id: "1.3-WQ9", difficulty: 2, correctId: "a", widget: "FinancialRatios", visualId: "a7", prompt: "Un D/E < 1 dans le FinancialRatios indique :", choices: c("Plus de fonds propres que de dette", "Plus de dette que de fonds propres", "Une absence totale de dette", "Une faillite imminente"), explanation: "Structure financière conservative." },
    { id: "1.3-WQ10", difficulty: 3, correctId: "a", widget: "FinancialRatios", visualId: "a7", prompt: "Pourquoi le ROE élevé via levier (dette) est-il signalé comme « fragile » dans le FinancialRatios ?", choices: c("Parce que la dette augmente le risque financier en cas de choc", "Parce que la dette est interdite", "Parce que le ROE est faux", "Parce que les actionnaires préfèrent le cash"), explanation: "ROE artificiellement gonflé = risque de faillite si les taux montent." },
    { id: "1.3-WQ11", difficulty: 3, correctId: "a", widget: "BalanceSheetExplorer", visualId: "a8", prompt: "Dans le BalanceSheetExplorer, le « Current Ratio » < 1 signifie concrètement :", choices: c("L'entreprise ne peut pas couvrir ses dettes à court terme avec ses actifs liquides", "L'entreprise est très rentable", "L'entreprise a trop de cash", "Rien de particulier"), explanation: "C'est un signal d'alerte de liquidité." },
    { id: "1.3-WQ12", difficulty: 3, correctId: "a", widget: "CompanyHealthScore", visualId: "a6", prompt: "Pourquoi le CompanyHealthScore pondère-t-il la « Croissance » à 30 % et la « Liquidité » à 20 % ?", choices: c("Parce que la croissance est le meilleur prédicteur de création de valeur à long terme", "Parce que la liquidité n'a pas d'importance", "Parce que les pondérations sont aléatoires", "Parce que la dette est plus importante"), explanation: "La croissance est le moteur principal, mais la liquidité reste critique (20 %)." },
  ],
  outils: [
    { id: "1.4-WQ1", difficulty: 1, correctId: "b", widget: "ValuationLab", visualId: "a12", prompt: "Le ValuationLab permet de tester :", choices: c("Les ratios de liquidité", "Les multiples P/E, P/S, P/B et leur prime/décote sectorielle", "Les taux de change", "L'inflation"), explanation: "C'est un laboratoire de valorisation par multiples." },
    { id: "1.4-WQ2", difficulty: 1, correctId: "b", widget: "DcfSimulator", visualId: "a12", prompt: "Dans le DcfSimulator, le paramètre le plus sensible est :", choices: c("La croissance des revenus", "Le WACC", "La marge nette", "Le nombre d'employés"), explanation: "+1 % WACC = −15 à −20 % valorisation." },
    { id: "1.4-WQ3", difficulty: 1, correctId: "a", widget: "PeerComparisonMatrix", visualId: "a12", prompt: "Le PeerComparisonMatrix compare une entreprise à :", choices: c("Des concurrents du même secteur", "Des entreprises aléatoires", "Des indices boursiers", "Des banques centrales"), explanation: "C'est la comparaison avec des pairs (peers)." },
    { id: "1.4-WQ4", difficulty: 2, correctId: "b", widget: "EarningsImpactEngine", visualId: "a12", prompt: "Dans l'EarningsImpactEngine, un « Beat + Guidance Lowered » est généralement interprété comme :", choices: c("Très positif", "Souvent négatif (le marché privilégie les perspectives)", "Neutre", "Sans impact"), explanation: "La guidance > beat actuel. Lowered = dégradation attendue." },
    { id: "1.4-WQ5", difficulty: 2, correctId: "b", widget: "DcfSimulator", visualId: "a12", prompt: "Le DcfSimulator affiche la « valeur terminale » comme représentant :", choices: c("5 % de la valorisation", "60-80 % de la valorisation totale", "La dette nette", "Les dividendes"), explanation: "La majorité de la valeur vient des flux lointains." },
    { id: "1.4-WQ6", difficulty: 2, correctId: "b", widget: "ValuationLab", visualId: "a12", prompt: "Dans le ValuationLab, un multiple supérieur à la médiane sectorielle signifie :", choices: c("Une décote automatique", "Une prime (croissance ou qualité supérieure)", "Une erreur de calcul", "Un red flag"), explanation: "Prime justifiée par des fondamentaux supérieurs." },
    { id: "1.4-WQ7", difficulty: 2, correctId: "b", widget: "PeerComparisonMatrix", visualId: "a12", prompt: "Le PeerComparisonMatrix identifie un « laggard » comme :", choices: c("Une entreprise avec ROE élevé et marges supérieures", "Une entreprise avec multiples bas et marges compressées", "Une entreprise en forte croissance", "Une entreprise sans dette"), explanation: "Laggard = sous-performeur structurel du secteur." },
    { id: "1.4-WQ8", difficulty: 2, correctId: "b", widget: "EarningsImpactEngine", visualId: "a12", prompt: "Dans l'EarningsImpactEngine, une surprise EPS > 5 % est considérée comme :", choices: c("Un bruit de marché", "Un fort signal", "Sans importance", "Un dividende exceptionnel"), explanation: "> 5 % = magnitude significative = réaction cours probable." },
    { id: "1.4-WQ9", difficulty: 3, correctId: "b", widget: "ValuationLab", visualId: "a12", prompt: "Pourquoi le ValuationLab suggère-t-il de tester la sensibilité EPS ± 10 % ?", choices: c("Parce que les résultats sont toujours faux", "Pour évaluer la robustesse de la valorisation face à l'incertitude", "Parce que c'est obligatoire", "Pour augmenter le P/E"), explanation: "Le stress testing des hypothèses est central en institutionnel." },
    { id: "1.4-WQ10", difficulty: 3, correctId: "b", widget: "DcfSimulator", visualId: "a12", prompt: "Dans le DcfSimulator, un taux de croissance perpétuel de 6 % est :", choices: c("Conservateur", "Agressif et probablement excessif", "Standard", "Interdit"), explanation: "La croissance perpétuelle ne peut excéder la croissance économique long terme (2-4 %)." },
    { id: "1.4-WQ11", difficulty: 3, correctId: "a", widget: "PeerComparisonMatrix", visualId: "a12", prompt: "Le PeerComparisonMatrix peut révéler un « value trap » quand :", choices: c("Le P/E est bas mais la croissance est négative et la dette élevée", "Le P/E est élevé", "L'entreprise est leader", "Le secteur est en expansion"), explanation: "Multiple bas justifié par la dégradation = pas d'opportunité." },
    { id: "1.4-WQ12", difficulty: 3, correctId: "a", widget: "EarningsImpactEngine", visualId: "a12", prompt: "Pourquoi l'EarningsImpactEngine croise-t-il le beat/miss avec la guidance ?", choices: c("Parce que la guidance oriente les attentes futures plus que le passé", "Parce que le passé n'a pas d'importance", "Parce que la guidance est obligatoire", "Parce que le beat est toujours positif"), explanation: "Le marché est forward-looking. La guidance pilote le réajustement des modèles." },
  ],
  previsions: [
    { id: "1.5-WQ1", difficulty: 1, correctId: "b", widget: "ForecastScenarioPlanner", visualId: "a15", prompt: "Le ForecastScenarioPlanner utilise :", choices: c("Un seul scénario", "3 scénarios (optimiste, neutre, pessimiste) + probabilités", "10 scénarios identiques", "Aucun scénario"), explanation: "La valeur espérée = Σ(probabilité × valorisation scénario)." },
    { id: "1.5-WQ2", difficulty: 1, correctId: "b", widget: "ScenarioBuilder", visualId: "a9", prompt: "Dans le ScenarioBuilder, un scénario valide doit contenir :", choices: c("Uniquement une thèse haussière", "Thèse + mécanisme + catalyseur + invalidation", "Un graphique technique", "Un ordre d'achat"), explanation: "Scénario = pourquoi + comment + quand + sortie." },
    { id: "1.5-WQ3", difficulty: 1, correctId: "b", widget: "ForecastScenarioPlanner", visualId: "a15", prompt: "La somme des probabilités des 3 scénarios dans le ForecastScenarioPlanner doit être :", choices: c("50 %", "100 %", "150 %", "Variable"), explanation: "C'est une distribution de probabilités complète." },
    { id: "1.5-WQ4", difficulty: 2, correctId: "b", widget: "ScenarioBuilder", visualId: "a9", prompt: "Le ScenarioBuilder force à définir une « invalidation » car :", choices: c("C'est une règle de l'AMF", "Sans invalidation = biais de confirmation, pas un vrai scénario", "Les stops sont obligatoires", "L'invalidation est optionnelle"), explanation: "Définir la sortie avant l'entrée = discipline institutionnelle." },
    { id: "1.5-WQ5", difficulty: 2, correctId: "a", widget: "ForecastScenarioPlanner", visualId: "a15", prompt: "Si la valeur espérée > cours actuel dans le ForecastScenarioPlanner, cela suggère :", choices: c("Une asymétrie positive (upside)", "Une surévaluation", "Un scénario sans risque", "Une erreur de calcul"), explanation: "L'asymétrie risque/rendement favorise l'achat." },
    { id: "1.5-WQ6", difficulty: 2, correctId: "a", widget: "ScenarioBuilder", visualId: "a9", prompt: "Dans le ScenarioBuilder, le « catalyseur » correspond à :", choices: c("Le moment précis où la thèse se déclenche", "La couleur du graphique", "Le dividende", "Le ratio D/E"), explanation: "Quand = événement déclencheur (publication, décision politique)." },
    { id: "1.5-WQ7", difficulty: 2, correctId: "a", widget: "ForecastScenarioPlanner", visualId: "a15", prompt: "Pourquoi le ForecastScenarioPlanner exige-t-il 3 scénarios et non 1 ?", choices: c("Parce que 1 scénario = absence de gestion du risque", "Parce que la loi l'exige", "Parce que les marchés sont prévisibles", "Parce que 3 est un chiffre magique"), explanation: "La préparation multi-scénarios = anticipation des différents états du monde." },
    { id: "1.5-WQ8", difficulty: 2, correctId: "b", widget: "ScenarioBuilder", visualId: "a9", prompt: "Dans le ScenarioBuilder, la « validation » d'un scénario correspond à :", choices: c("L'acceptation par la banque centrale", "Les conditions confirmant que la thèse se matérialise", "Un algorithme", "Un consensus d'analystes"), explanation: "C'est le miroir de l'invalidation : quand est-ce que je sais que j'ai raison ?" },
    { id: "1.5-WQ9", difficulty: 3, correctId: "a", widget: "ForecastScenarioPlanner", visualId: "a15", prompt: "Une probabilité de 70 % au scénario neutre et 15 % aux extrêmes dans le ForecastScenarioPlanner suggère :", choices: c("Une confiance élevée dans le scénario central", "Une incertitude extrême", "Un marché efficient", "Une erreur de modélisation"), explanation: "Distribution concentrée = faible volatilité attendue, scénario central dominant." },
    { id: "1.5-WQ10", difficulty: 3, correctId: "a", widget: "ScenarioBuilder", visualId: "a9", prompt: "Pourquoi le ScenarioBuilder inclut-il une étape « export » du scénario ?", choices: c("Pour le partager et le suivre dans un journal de trading", "Pour l'imprimer en couleur", "Parce que c'est obligatoire", "Pour le vendre"), explanation: "L'export permet le suivi, la rétrospective et l'amélioration du processus décisionnel." },
  ],
};

export const PART_B_LESSON_IDS = Object.keys(PART_B_BANK) as CoreLessonId[];
