/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyAnalyseFondamentaleRouteImport } from './routes/academy.analyse-fondamentale'
import { Route as AcademyAnalyseFondamentaleCertificationRouteImport } from './routes/academy.analyse-fondamentale.certification'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAnalyseFondamentaleRoute =
  AcademyAnalyseFondamentaleRouteImport.update({
    id: '/academy/analyse-fondamentale',
    path: '/academy/analyse-fondamentale',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyAnalyseFondamentaleCertificationRoute =
  AcademyAnalyseFondamentaleCertificationRouteImport.update({
    id: '/certification',
    path: '/certification',
    getParentRoute: () => AcademyAnalyseFondamentaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/academy/analyse-fondamentale/certification': typeof AcademyAnalyseFondamentaleCertificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRouteWithChildren
  '/academy': typeof AcademyIndexRoute
  '/academy/analyse-fondamentale/certification': typeof AcademyAnalyseFondamentaleCertificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/academy/analyse-fondamentale/certification': typeof AcademyAnalyseFondamentaleCertificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/academy/analyse-fondamentale'
    | '/academy/'
    | '/academy/analyse-fondamentale/certification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/academy/analyse-fondamentale'
    | '/academy'
    | '/academy/analyse-fondamentale/certification'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/academy/analyse-fondamentale'
    | '/academy/'
    | '/academy/analyse-fondamentale/certification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AcademyAnalyseFondamentaleRoute: typeof AcademyAnalyseFondamentaleRouteWithChildren
  AcademyIndexRoute: typeof AcademyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/analyse-fondamentale': {
      id: '/academy/analyse-fondamentale'
      path: '/academy/analyse-fondamentale'
      fullPath: '/academy/analyse-fondamentale'
      preLoaderRoute: typeof AcademyAnalyseFondamentaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/analyse-fondamentale/certification': {
      id: '/academy/analyse-fondamentale/certification'
      path: '/certification'
      fullPath: '/academy/analyse-fondamentale/certification'
      preLoaderRoute: typeof AcademyAnalyseFondamentaleCertificationRouteImport
      parentRoute: typeof AcademyAnalyseFondamentaleRoute
    }
  }
}

interface AcademyAnalyseFondamentaleRouteChildren {
  AcademyAnalyseFondamentaleCertificationRoute: typeof AcademyAnalyseFondamentaleCertificationRoute
}

const AcademyAnalyseFondamentaleRouteChildren: AcademyAnalyseFondamentaleRouteChildren =
  {
    AcademyAnalyseFondamentaleCertificationRoute:
      AcademyAnalyseFondamentaleCertificationRoute,
  }

const AcademyAnalyseFondamentaleRouteWithChildren =
  AcademyAnalyseFondamentaleRoute._addFileChildren(
    AcademyAnalyseFondamentaleRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AcademyAnalyseFondamentaleRoute: AcademyAnalyseFondamentaleRouteWithChildren,
  AcademyIndexRoute: AcademyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
