/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyAnalyseFondamentaleRouteImport } from './routes/academy.analyse-fondamentale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAnalyseFondamentaleRoute =
  AcademyAnalyseFondamentaleRouteImport.update({
    id: '/academy/analyse-fondamentale',
    path: '/academy/analyse-fondamentale',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy/analyse-fondamentale': typeof AcademyAnalyseFondamentaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/academy/analyse-fondamentale'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/academy/analyse-fondamentale'
  id: '__root__' | '/' | '/academy/analyse-fondamentale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyAnalyseFondamentaleRoute: typeof AcademyAnalyseFondamentaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/analyse-fondamentale': {
      id: '/academy/analyse-fondamentale'
      path: '/academy/analyse-fondamentale'
      fullPath: '/academy/analyse-fondamentale'
      preLoaderRoute: typeof AcademyAnalyseFondamentaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyAnalyseFondamentaleRoute: AcademyAnalyseFondamentaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
