/*
# Insert Part B questions (batch 2 of 2)

Inserts 27 remaining Part B questions (micro rest + outils + previsions lessons) into question_bank_part_b.
This completes the 59-question Part B dataset. Data-only migration — no schema changes.
*/

INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ5', 'analyse-fondamentale', 'micro', 2, 'Dans le FinancialRatios, un ROE > 15 % est généralement considéré comme :', '[{"id":"a","label":"Faible"},{"id":"b","label":"De qualité institutionnelle"},{"id":"c","label":"Négatif"},{"id":"d","label":"Sans importance"}]'::jsonb, 'b', 'Seuil classique de rentabilité des fonds propres.', 'FinancialRatios', 'a7', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ6', 'analyse-fondamentale', 'micro', 2, 'Le Current Ratio dans le FinancialRatios mesure :', '[{"id":"a","label":"La rentabilité"},{"id":"b","label":"La liquidité à court terme (actifs courants / dettes courantes)"},{"id":"c","label":"L''endettement total"},{"id":"d","label":"La croissance"}]'::jsonb, 'b', '< 1 = risque de défaut à court terme.', 'FinancialRatios', 'a7', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ7', 'analyse-fondamentale', 'micro', 2, 'Dans le BalanceSheetExplorer, si Actif < Passif, l''entreprise est :', '[{"id":"a","label":"Très rentable"},{"id":"b","label":"Techniquement insolvable"},{"id":"c","label":"En croissance"},{"id":"d","label":"Sous-évaluée"}]'::jsonb, 'b', 'L''équilibre comptable est rompu = insolvabilité technique.', 'BalanceSheetExplorer', 'a8', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ8', 'analyse-fondamentale', 'micro', 2, 'Le CompanyDashboard suggère qu''un seul KPI « ne raconte rien ». Pourquoi ?', '[{"id":"a","label":"Parce que les KPI sont faux"},{"id":"b","label":"Parce qu''il faut croiser Croissance + Marges + Dette + Cash"},{"id":"c","label":"Parce que le dashboard est inutile"},{"id":"d","label":"Parce que les marchés sont efficients"}]'::jsonb, 'b', 'La microéconomie exige la lecture croisée (ex: profitable + surendetté = fragile).', 'CompanyDashboard', 'a3', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ9', 'analyse-fondamentale', 'micro', 2, 'Un D/E < 1 dans le FinancialRatios indique :', '[{"id":"a","label":"Plus de fonds propres que de dette"},{"id":"b","label":"Plus de dette que de fonds propres"},{"id":"c","label":"Une absence totale de dette"},{"id":"d","label":"Une faillite imminente"}]'::jsonb, 'a', 'Structure financière conservative.', 'FinancialRatios', 'a7', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ10', 'analyse-fondamentale', 'micro', 3, 'Pourquoi le ROE élevé via levier (dette) est-il signalé comme « fragile » dans le FinancialRatios ?', '[{"id":"a","label":"Parce que la dette augmente le risque financier en cas de choc"},{"id":"b","label":"Parce que la dette est interdite"},{"id":"c","label":"Parce que le ROE est faux"},{"id":"d","label":"Parce que les actionnaires préfèrent le cash"}]'::jsonb, 'a', 'ROE artificiellement gonflé = risque de faillite si les taux montent.', 'FinancialRatios', 'a7', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ11', 'analyse-fondamentale', 'micro', 3, 'Dans le BalanceSheetExplorer, le « Current Ratio » < 1 signifie concrètement :', '[{"id":"a","label":"L''entreprise ne peut pas couvrir ses dettes à court terme avec ses actifs liquides"},{"id":"b","label":"L''entreprise est très rentable"},{"id":"c","label":"L''entreprise a trop de cash"},{"id":"d","label":"Rien de particulier"}]'::jsonb, 'a', 'C''est un signal d''alerte de liquidité.', 'BalanceSheetExplorer', 'a8', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.3-WQ12', 'analyse-fondamentale', 'micro', 3, 'Pourquoi le CompanyHealthScore pondère-t-il la « Croissance » à 30 % et la « Liquidité » à 20 % ?', '[{"id":"a","label":"Parce que la croissance est le meilleur prédicteur de création de valeur à long terme"},{"id":"b","label":"Parce que la liquidité n''a pas d''importance"},{"id":"c","label":"Parce que les pondérations sont aléatoires"},{"id":"d","label":"Parce que la dette est plus importante"}]'::jsonb, 'a', 'La croissance est le moteur principal, mais la liquidité reste critique (20 %).', 'CompanyHealthScore', 'a6', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ1', 'analyse-fondamentale', 'outils', 1, 'Le ValuationLab permet de tester :', '[{"id":"a","label":"Les ratios de liquidité"},{"id":"b","label":"Les multiples P/E, P/S, P/B et leur prime/décote sectorielle"},{"id":"c","label":"Les taux de change"},{"id":"d","label":"L''inflation"}]'::jsonb, 'b', 'C''est un laboratoire de valorisation par multiples.', 'ValuationLab', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ2', 'analyse-fondamentale', 'outils', 1, 'Dans le DcfSimulator, le paramètre le plus sensible est :', '[{"id":"a","label":"La croissance des revenus"},{"id":"b","label":"Le WACC"},{"id":"c","label":"La marge nette"},{"id":"d","label":"Le nombre d''employés"}]'::jsonb, 'b', '+1 % WACC = −15 à −20 % valorisation.', 'DcfSimulator', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ3', 'analyse-fondamentale', 'outils', 1, 'Le PeerComparisonMatrix compare une entreprise à :', '[{"id":"a","label":"Des concurrents du même secteur"},{"id":"b","label":"Des entreprises aléatoires"},{"id":"c","label":"Des indices boursiers"},{"id":"d","label":"Des banques centrales"}]'::jsonb, 'a', 'C''est la comparaison avec des pairs (peers).', 'PeerComparisonMatrix', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ4', 'analyse-fondamentale', 'outils', 2, 'Dans l''EarningsImpactEngine, un « Beat + Guidance Lowered » est généralement interprété comme :', '[{"id":"a","label":"Très positif"},{"id":"b","label":"Souvent négatif (le marché privilégie les perspectives)"},{"id":"c","label":"Neutre"},{"id":"d","label":"Sans impact"}]'::jsonb, 'b', 'La guidance > beat actuel. Lowered = dégradation attendue.', 'EarningsImpactEngine', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ5', 'analyse-fondamentale', 'outils', 2, 'Le DcfSimulator affiche la « valeur terminale » comme représentant :', '[{"id":"a","label":"5 % de la valorisation"},{"id":"b","label":"60-80 % de la valorisation totale"},{"id":"c","label":"La dette nette"},{"id":"d","label":"Les dividendes"}]'::jsonb, 'b', 'La majorité de la valeur vient des flux lointains.', 'DcfSimulator', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ6', 'analyse-fondamentale', 'outils', 2, 'Dans le ValuationLab, un multiple supérieur à la médiane sectorielle signifie :', '[{"id":"a","label":"Une décote automatique"},{"id":"b","label":"Une prime (croissance ou qualité supérieure)"},{"id":"c","label":"Une erreur de calcul"},{"id":"d","label":"Un red flag"}]'::jsonb, 'b', 'Prime justifiée par des fondamentaux supérieurs.', 'ValuationLab', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ7', 'analyse-fondamentale', 'outils', 2, 'Le PeerComparisonMatrix identifie un « laggard » comme :', '[{"id":"a","label":"Une entreprise avec ROE élevé et marges supérieures"},{"id":"b","label":"Une entreprise avec multiples bas et marges compressées"},{"id":"c","label":"Une entreprise en forte croissance"},{"id":"d","label":"Une entreprise sans dette"}]'::jsonb, 'b', 'Laggard = sous-performeur structurel du secteur.', 'PeerComparisonMatrix', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ8', 'analyse-fondamentale', 'outils', 2, 'Dans l''EarningsImpactEngine, une surprise EPS > 5 % est considérée comme :', '[{"id":"a","label":"Un bruit de marché"},{"id":"b","label":"Un fort signal"},{"id":"c","label":"Sans importance"},{"id":"d","label":"Un dividende exceptionnel"}]'::jsonb, 'b', '> 5 % = magnitude significative = réaction cours probable.', 'EarningsImpactEngine', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ9', 'analyse-fondamentale', 'outils', 3, 'Pourquoi le ValuationLab suggère-t-il de tester la sensibilité EPS ± 10 % ?', '[{"id":"a","label":"Parce que les résultats sont toujours faux"},{"id":"b","label":"Pour évaluer la robustesse de la valorisation face à l''incertitude"},{"id":"c","label":"Parce que c''est obligatoire"},{"id":"d","label":"Pour augmenter le P/E"}]'::jsonb, 'b', 'Le stress testing des hypothèses est central en institutionnel.', 'ValuationLab', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ10', 'analyse-fondamentale', 'outils', 3, 'Dans le DcfSimulator, un taux de croissance perpétuel de 6 % est :', '[{"id":"a","label":"Conservateur"},{"id":"b","label":"Agressif et probablement excessif"},{"id":"c","label":"Standard"},{"id":"d","label":"Interdit"}]'::jsonb, 'b', 'La croissance perpétuelle ne peut excéder la croissance économique long terme (2-4 %).', 'DcfSimulator', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ11', 'analyse-fondamentale', 'outils', 3, 'Le PeerComparisonMatrix peut révéler un « value trap » quand :', '[{"id":"a","label":"Le P/E est bas mais la croissance est négative et la dette élevée"},{"id":"b","label":"Le P/E est élevé"},{"id":"c","label":"L''entreprise est leader"},{"id":"d","label":"Le secteur est en expansion"}]'::jsonb, 'a', 'Multiple bas justifié par la dégradation = pas d''opportunité.', 'PeerComparisonMatrix', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.4-WQ12', 'analyse-fondamentale', 'outils', 3, 'Pourquoi l''EarningsImpactEngine croise-t-il le beat/miss avec la guidance ?', '[{"id":"a","label":"Parce que la guidance oriente les attentes futures plus que le passé"},{"id":"b","label":"Parce que le passé n''a pas d''importance"},{"id":"c","label":"Parce que la guidance est obligatoire"},{"id":"d","label":"Parce que le beat est toujours positif"}]'::jsonb, 'a', 'Le marché est forward-looking. La guidance pilote le réajustement des modèles.', 'EarningsImpactEngine', 'a12', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ1', 'analyse-fondamentale', 'previsions', 1, 'Le ForecastScenarioPlanner utilise :', '[{"id":"a","label":"Un seul scénario"},{"id":"b","label":"3 scénarios (optimiste, neutre, pessimiste) + probabilités"},{"id":"c","label":"10 scénarios identiques"},{"id":"d","label":"Aucun scénario"}]'::jsonb, 'b', 'La valeur espérée = Σ(probabilité × valorisation scénario).', 'ForecastScenarioPlanner', 'a15', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ2', 'analyse-fondamentale', 'previsions', 1, 'Dans le ScenarioBuilder, un scénario valide doit contenir :', '[{"id":"a","label":"Uniquement une thèse haussière"},{"id":"b","label":"Thèse + mécanisme + catalyseur + invalidation"},{"id":"c","label":"Un graphique technique"},{"id":"d","label":"Un ordre d''achat"}]'::jsonb, 'b', 'Scénario = pourquoi + comment + quand + sortie.', 'ScenarioBuilder', 'a9', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ3', 'analyse-fondamentale', 'previsions', 1, 'La somme des probabilités des 3 scénarios dans le ForecastScenarioPlanner doit être :', '[{"id":"a","label":"50 %"},{"id":"b","label":"100 %"},{"id":"c","label":"150 %"},{"id":"d","label":"Variable"}]'::jsonb, 'b', 'C''est une distribution de probabilités complète.', 'ForecastScenarioPlanner', 'a15', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ4', 'analyse-fondamentale', 'previsions', 2, 'Le ScenarioBuilder force à définir une « invalidation » car :', '[{"id":"a","label":"C''est une règle de l''AMF"},{"id":"b","label":"Sans invalidation = biais de confirmation, pas un vrai scénario"},{"id":"c","label":"Les stops sont obligatoires"},{"id":"d","label":"L''invalidation est optionnelle"}]'::jsonb, 'b', 'Définir la sortie avant l''entrée = discipline institutionnelle.', 'ScenarioBuilder', 'a9', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ5', 'analyse-fondamentale', 'previsions', 2, 'Si la valeur espérée > cours actuel dans le ForecastScenarioPlanner, cela suggère :', '[{"id":"a","label":"Une asymétrie positive (upside)"},{"id":"b","label":"Une surévaluation"},{"id":"c","label":"Un scénario sans risque"},{"id":"d","label":"Une erreur de calcul"}]'::jsonb, 'a', 'L''asymétrie risque/rendement favorise l''achat.', 'ForecastScenarioPlanner', 'a15', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ6', 'analyse-fondamentale', 'previews', 2, 'Dans le ScenarioBuilder, le « catalyseur » correspond à :', '[{"id":"a","label":"Le moment précis où la thèse se déclenche"},{"id":"b","label":"La couleur du graphique"},{"id":"c","label":"Le dividende"},{"id":"d","label":"Le ratio D/E"}]'::jsonb, 'a', 'Quand = événement déclencheur (publication, décision politique).', 'ScenarioBuilder', 'a9', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ7', 'analyse-fondamentale', 'previsions', 2, 'Pourquoi le ForecastScenarioPlanner exige-t-il 3 scénarios et non 1 ?', '[{"id":"a","label":"Parce que 1 scénario = absence de gestion du risque"},{"id":"b","label":"Parce que la loi l''exige"},{"id":"c","label":"Parce que les marchés sont prévisibles"},{"id":"d","label":"Parce que 3 est un chiffre magique"}]'::jsonb, 'a', 'La préparation multi-scénarios = anticipation des différents états du monde.', 'ForecastScenarioPlanner', 'a15', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ8', 'analyse-fondamentale', 'previsions', 2, 'Dans le ScenarioBuilder, la « validation » d''un scénario correspond à :', '[{"id":"a","label":"L''acceptation par la banque centrale"},{"id":"b","label":"Les conditions confirmant que la thèse se matérialise"},{"id":"c","label":"Un algorithme"},{"id":"d","label":"Un consensus d''analystes"}]'::jsonb, 'b', 'C''est le miroir de l''invalidation : quand est-ce que je sais que j''ai raison ?', 'ScenarioBuilder', 'a9', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ9', 'analyse-fondamentale', 'previsions', 3, 'Une probabilité de 70 % au scénario neutre et 15 % aux extrêmes dans le ForecastScenarioPlanner suggère :', '[{"id":"a","label":"Une confiance élevée dans le scénario central"},{"id":"b","label":"Une incertitude extrême"},{"id":"c","label":"Un marché efficient"},{"id":"d","label":"Une erreur de modélisation"}]'::jsonb, 'a', 'Distribution concentrée = faible volatilité attendue, scénario central dominant.', 'ForecastScenarioPlanner', 'a15', true);
INSERT INTO question_bank_part_b (question_key, chapter_id, lesson_id, difficulty, prompt, choices, correct_id, explanation, widget, visual_id, is_active) VALUES ('1.5-WQ10', 'analyse-fondamentale', 'previsions', 3, 'Pourquoi le ScenarioBuilder inclut-il une étape « export » du scénario ?', '[{"id":"a","label":"Pour le partager et le suivre dans un journal de trading"},{"id":"b","label":"Pour l''imprimer en couleur"},{"id":"c","label":"Parce que c''est obligatoire"},{"id":"d","label":"Pour le vendre"}]'::jsonb, 'a', 'L''export permet le suivi, la rétrospective et l''amélioration du processus décisionnel.', 'ScenarioBuilder', 'a9', true);